name: ci

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: Cache gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: echo
      run: |
        echo ${{ env.JAVA_HOME_17_X64 }}
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        echo "EUISANG 1"
        echo $JAVA_HOME
        echo "EUISANG 2"
        echo $PATH
        echo "EUISANG 3"

    - name: Build with gradle
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
      run: |
        echo "EUISANG 1"
        echo $JAVA_HOME
        echo "EUISANG 2"
        ./gradlew build jacocoTestCoverageReport detekt

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

